<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-07 at 14:12:25.
 */
class ConfiguracaoEmpresaServiceTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ConfiguracaoEmpresaService
     */
    protected $object;
    protected $session;
    protected static $cliente = null;
    protected static $config;
    
    public static function setUpBeforeClass()
    {
        self::$config = require("config.php");
        self::$config = self::$config[self::$config["running"]];
    }
    
    protected function setUp()
    {
        $this->session = new NashEarlySession(self::$config['servicePath']);
        $this->session->login(self::$config);
        
        $this->object = new ConfiguracaoEmpresaService($this->session);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Nash\Client\Services\ConfiguracaoEmpresaService::getConfiguracao
     * @todo   Implement testGetConfiguracao().
     */
    public function testGetConfiguracao()
    {
        $result = $this->object->getConfiguracao();
        $this->assertEquals(Result::SUCCESS, $result->getStatus());
        $this->assertNotNull($result->getModel());
        $this->assertInstanceOf("ConfiguracaoEmpresa", $result->getModel());
    }
}
